"""add profile lookup tables

Revision ID: 1c38887bedf9
Revises: d959cb5123ae
Create Date: 2026-07-20 12:35:22.377032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c38887bedf9'
down_revision: Union[str, Sequence[str], None] = 'd959cb5123ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allergens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_allergens_id'), 'allergens', ['id'], unique=False)
    op.create_table('dietary_styles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_dietary_styles_id'), 'dietary_styles', ['id'], unique=False)
    op.create_table('medical_restrictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_medical_restrictions_id'), 'medical_restrictions', ['id'], unique=False)
    op.create_table('nutrition_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_nutrition_goals_id'), 'nutrition_goals', ['id'], unique=False)
    op.create_table('user_allergens',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('allergen_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['allergen_id'], ['allergens.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'allergen_id')
    )
    op.create_table('user_dietary_styles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('dietary_style_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dietary_style_id'], ['dietary_styles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'dietary_style_id')
    )
    op.create_table('user_medical_restrictions',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('medical_restriction_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['medical_restriction_id'], ['medical_restrictions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'medical_restriction_id')
    )
    op.create_table('user_nutrition_goals',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nutrition_goal_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['nutrition_goal_id'], ['nutrition_goals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'nutrition_goal_id')
    )
    # ### end Alembic commands ###

    # Seed reference data (reconciled from 02_FEATURES.md and 04_DATABASE.md)
    allergens_table = sa.table(
        "allergens", sa.column("name", sa.String)
    )
    op.bulk_insert(
        allergens_table,
        [
            {"name": name}
            for name in [
                "Peanut",
                "Tree Nut",
                "Dairy",
                "Egg",
                "Soy",
                "Wheat",
                "Fish",
                "Shellfish",
                "Sesame",
            ]
        ],
    )

    medical_restrictions_table = sa.table(
        "medical_restrictions", sa.column("name", sa.String)
    )
    op.bulk_insert(
        medical_restrictions_table,
        [
            {"name": name}
            for name in [
                "Celiac Disease",
                "Gluten Intolerance",
                "Lactose Intolerance",
                "Low FODMAP",
            ]
        ],
    )

    dietary_styles_table = sa.table(
        "dietary_styles", sa.column("name", sa.String)
    )
    op.bulk_insert(
        dietary_styles_table,
        [
            {"name": name}
            for name in [
                "Vegan",
                "Vegetarian",
                "Pescatarian",
                "Mediterranean",
                "Anti-inflammatory",
            ]
        ],
    )

    nutrition_goals_table = sa.table(
        "nutrition_goals", sa.column("name", sa.String)
    )
    op.bulk_insert(
        nutrition_goals_table,
        [
            {"name": name}
            for name in [
                "Weight Loss",
                "Muscle Gain",
                "Weight Maintenance",
                "High Protein",
                "Low Carb",
            ]
        ],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_nutrition_goals')
    op.drop_table('user_medical_restrictions')
    op.drop_table('user_dietary_styles')
    op.drop_table('user_allergens')
    op.drop_index(op.f('ix_nutrition_goals_id'), table_name='nutrition_goals')
    op.drop_table('nutrition_goals')
    op.drop_index(op.f('ix_medical_restrictions_id'), table_name='medical_restrictions')
    op.drop_table('medical_restrictions')
    op.drop_index(op.f('ix_dietary_styles_id'), table_name='dietary_styles')
    op.drop_table('dietary_styles')
    op.drop_index(op.f('ix_allergens_id'), table_name='allergens')
    op.drop_table('allergens')
    # ### end Alembic commands ###
