"""add ingredient cache table

Revision ID: fc8e5b064811
Revises: d109f7c37a72
Create Date: 2026-07-22 15:20:08.317347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fc8e5b064811'
down_revision: Union[str, Sequence[str], None] = 'd109f7c37a72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredient_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingredient_name', sa.String(), nullable=False),
    sa.Column('found', sa.Boolean(), nullable=False),
    sa.Column('health_labels', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('nutrients', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingredient_cache_id'), 'ingredient_cache', ['id'], unique=False)
    op.create_index(op.f('ix_ingredient_cache_ingredient_name'), 'ingredient_cache', ['ingredient_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ingredient_cache_ingredient_name'), table_name='ingredient_cache')
    op.drop_index(op.f('ix_ingredient_cache_id'), table_name='ingredient_cache')
    op.drop_table('ingredient_cache')
    # ### end Alembic commands ###
